const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const files = ['manifest.json', 'core.js', 'background.js', 'panel.js', 'content.js', 'popup.html', 'popup.css', 'README.md'];
const target = path.resolve('outputs/chzz-shortcut');
fs.mkdirSync(target, { recursive: true });
for (const file of files) fs.copyFileSync(file, path.join(target, file));
const { version } = require('../package.json');
const zip = path.resolve(`outputs/chzz-shortcut-${version}.zip`);
fs.rmSync(zip, { force: true });
execFileSync('zip', ['-q', zip, ...files], { cwd: target });
console.log(`Unpacked: ${target}\nZIP: ${zip}`);
